#!/usr/bin/env node
/**
 * SocialPilot Pro — First-time setup script
 * Run: node scripts/setup.js
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const readline = require('readline');

const ROOT = path.join(__dirname, '..');
const ENV_EXAMPLE = path.join(ROOT, '.env.example');
const ENV_FILE = path.join(ROOT, '.env');

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise((res) => rl.question(q, res));

function generateSecret(bytes = 32) {
  return crypto.randomBytes(bytes).toString('hex');
}

async function main() {
  console.log('\n╔══════════════════════════════════════════╗');
  console.log('║     SocialPilot Pro — Setup Wizard       ║');
  console.log('╚══════════════════════════════════════════╝\n');

  if (fs.existsSync(ENV_FILE)) {
    const overwrite = await ask('⚠️  .env already exists. Overwrite? (y/N): ');
    if (overwrite.toLowerCase() !== 'y') {
      console.log('Setup cancelled. Existing .env kept.');
      rl.close();
      return;
    }
  }

  console.log('📋 Let\'s configure your environment.\n');

  // ── Database ──────────────────────────────────────────────
  console.log('── Database ─────────────────────────────────');
  const dbUrl = await ask('PostgreSQL URL [postgresql://postgres:password@localhost:5432/socialpilot_dev]: ');

  // ── App URLs ──────────────────────────────────────────────
  console.log('\n── App URLs ─────────────────────────────────');
  const frontendUrl = await ask('Frontend URL [http://localhost:4200]: ');
  const backendUrl  = await ask('Backend URL  [http://localhost:3000]: ');

  // ── Meta API ──────────────────────────────────────────────
  console.log('\n── Meta (Facebook + Instagram) ──────────────');
  console.log('  Get credentials at: https://developers.facebook.com');
  const fbAppId     = await ask('Facebook App ID     [leave blank to skip]: ');
  const fbAppSecret = await ask('Facebook App Secret [leave blank to skip]: ');

  // ── YouTube ───────────────────────────────────────────────
  console.log('\n── YouTube / Google ─────────────────────────');
  console.log('  Get credentials at: https://console.cloud.google.com');
  const ytClientId     = await ask('YouTube Client ID     [leave blank to skip]: ');
  const ytClientSecret = await ask('YouTube Client Secret [leave blank to skip]: ');
  const googleClientId     = ytClientId;
  const googleClientSecret = ytClientSecret;

  // ── Stripe ────────────────────────────────────────────────
  console.log('\n── Stripe Billing ───────────────────────────');
  console.log('  Get credentials at: https://dashboard.stripe.com');
  const stripePublishable = await ask('Stripe Publishable Key [leave blank to skip]: ');
  const stripeSecret      = await ask('Stripe Secret Key      [leave blank to skip]: ');
  const stripeWebhook     = await ask('Stripe Webhook Secret  [leave blank to skip]: ');

  // ── Stripe Price IDs ──────────────────────────────────────
  let proMonthly = '', proYearly = '', agencyMonthly = '', agencyYearly = '';
  if (stripeSecret) {
    console.log('\n── Stripe Price IDs (from your Stripe dashboard) ──');
    proMonthly     = await ask('Pro Monthly Price ID     [leave blank to skip]: ');
    proYearly      = await ask('Pro Yearly Price ID      [leave blank to skip]: ');
    agencyMonthly  = await ask('Agency Monthly Price ID  [leave blank to skip]: ');
    agencyYearly   = await ask('Agency Yearly Price ID   [leave blank to skip]: ');
  }

  // ── Email ─────────────────────────────────────────────────
  console.log('\n── Email (Resend) ───────────────────────────');
  const resendKey   = await ask('Resend API Key [leave blank to skip]: ');
  const emailFrom   = await ask('From email     [noreply@socialpilotpro.com]: ');

  // ── Ollama ────────────────────────────────────────────────
  console.log('\n── AI (Ollama) ──────────────────────────────');
  const ollamaUrl   = await ask('Ollama URL   [http://localhost:11434]: ');
  const ollamaModel = await ask('Ollama model [llama3.2]: ');

  // ── Generate secrets ──────────────────────────────────────
  const jwtSecret       = generateSecret(48);
  const encryptionKey   = generateSecret(32);

  // ── Build .env ────────────────────────────────────────────
  const env = `# ============================================================
# SocialPilot Pro — Environment Configuration
# Generated by setup.js on ${new Date().toISOString()}
# ============================================================

# ── App ──────────────────────────────────────────────────────
APP_NAME="SocialPilot Pro"
NODE_ENV="development"

# ── Database ─────────────────────────────────────────────────
DATABASE_URL="${dbUrl || 'postgresql://postgres:password@localhost:5432/socialpilot_dev'}"

# ── Auth ─────────────────────────────────────────────────────
JWT_SECRET="${jwtSecret}"
JWT_EXPIRY="7d"
TOKEN_ENCRYPTION_KEY="${encryptionKey}"

# ── URLs ─────────────────────────────────────────────────────
FRONTEND_URL="${frontendUrl || 'http://localhost:4200'}"
NEXT_PUBLIC_BACKEND_URL="${backendUrl || 'http://localhost:3000'}"
BACKEND_INTERNAL_URL="${backendUrl || 'http://localhost:3000'}"

# ── Storage ──────────────────────────────────────────────────
STORAGE_PROVIDER="local"
UPLOAD_DIRECTORY="./uploads"
NEXT_PUBLIC_UPLOAD_STATIC_DIRECTORY="/uploads"

# ── Meta (Facebook + Instagram) ──────────────────────────────
FACEBOOK_APP_ID="${fbAppId}"
FACEBOOK_APP_SECRET="${fbAppSecret}"
META_API_VERSION="v21.0"

# ── YouTube / Google ─────────────────────────────────────────
YOUTUBE_CLIENT_ID="${ytClientId}"
YOUTUBE_CLIENT_SECRET="${ytClientSecret}"
GOOGLE_CLIENT_ID="${googleClientId}"
GOOGLE_CLIENT_SECRET="${googleClientSecret}"

# ── Stripe ───────────────────────────────────────────────────
STRIPE_PUBLISHABLE_KEY="${stripePublishable}"
STRIPE_SECRET_KEY="${stripeSecret}"
STRIPE_SIGNING_KEY="${stripeWebhook}"
STRIPE_TAX_ENABLED="false"
STRIPE_PRICE_PRO_MONTHLY="${proMonthly}"
STRIPE_PRICE_PRO_YEARLY="${proYearly}"
STRIPE_PRICE_AGENCY_MONTHLY="${agencyMonthly}"
STRIPE_PRICE_AGENCY_YEARLY="${agencyYearly}"

# ── Email ─────────────────────────────────────────────────────
${resendKey ? `RESEND_API_KEY="${resendKey}"` : '# RESEND_API_KEY=""'}
EMAIL_FROM_ADDRESS="${emailFrom || 'noreply@socialpilotpro.com'}"
EMAIL_FROM_NAME="SocialPilot Pro"

# ── AI (Ollama) ───────────────────────────────────────────────
OLLAMA_BASE_URL="${ollamaUrl || 'http://localhost:11434'}"
OLLAMA_MODEL="${ollamaModel || 'llama3.2'}"

# ── Analytics Pipeline Cron ───────────────────────────────────
CRON_BASIC_STATS="*/15 * * * *"
CRON_POST_METRICS="0 * * * *"
CRON_FULL_ANALYTICS="0 2 * * *"

# ── Feature Flags ─────────────────────────────────────────────
ENABLE_MEDIA_PROCESSING="true"
ENABLE_AI_FEATURES="true"
ENABLE_PDF_REPORTS="true"
ENABLE_CHATBOT="true"

# ── Security ──────────────────────────────────────────────────
RATE_LIMIT_TTL="60"
RATE_LIMIT_MAX="100"

# ── Misc ──────────────────────────────────────────────────────
NX_ADD_PLUGINS=false
IS_GENERAL="true"
FEE_AMOUNT=0.05
API_LIMIT=30
`;

  fs.writeFileSync(ENV_FILE, env);
  console.log('\n✅ .env file created successfully!\n');

  // ── Next steps ────────────────────────────────────────────
  console.log('╔══════════════════════════════════════════╗');
  console.log('║           Next Steps                     ║');
  console.log('╚══════════════════════════════════════════╝');
  console.log('');
  console.log('1. Install dependencies:');
  console.log('   npm install -g pnpm@10.6.1');
  console.log('   pnpm install');
  console.log('');
  console.log('2. Start the database:');
  console.log('   pnpm dev:docker');
  console.log('   (or start PostgreSQL manually)');
  console.log('');
  console.log('3. Push database schema:');
  console.log('   pnpm prisma-db-push');
  console.log('');
  console.log('4. Seed initial data:');
  console.log('   pnpm prisma-seed');
  console.log('');
  console.log('5. Start Ollama (for AI features):');
  console.log('   ollama pull llama3.2');
  console.log('   ollama serve');
  console.log('');
  console.log('6. Start the development server:');
  console.log('   pnpm dev');
  console.log('');
  console.log('7. Open in browser:');
  console.log(`   Frontend: ${frontendUrl || 'http://localhost:4200'}`);
  console.log(`   API Docs: ${backendUrl || 'http://localhost:3000'}/api/docs`);
  console.log('');

  rl.close();
}

main().catch((e) => {
  console.error(e);
  rl.close();
  process.exit(1);
});
