import { Injectable, Logger } from '@nestjs/common';
import * as puppeteer from 'puppeteer';
import * as path from 'path';
import * as fs from 'fs';

@Injectable()
export class PdfService {
  private readonly logger = new Logger(PdfService.name);
  private readonly reportsDir = path.join(process.cwd(), 'reports', 'pdf');

  constructor() {
    if (!fs.existsSync(this.reportsDir)) {
      fs.mkdirSync(this.reportsDir, { recursive: true });
    }
  }

  async generateReport(html: string, filename: string): Promise<string> {
    const outputPath = path.join(this.reportsDir, `${filename}.pdf`);

    const browser = await puppeteer.launch({
      headless: true,
      args: ['--no-sandbox', '--disable-setuid-sandbox'],
    });

    try {
      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: 'networkidle0' });
      await page.pdf({
        path: outputPath,
        format: 'A4',
        printBackground: true,
        margin: { top: '20mm', right: '15mm', bottom: '20mm', left: '15mm' },
      });

      this.logger.log(`PDF generated: ${outputPath}`);
      return outputPath;
    } finally {
      await browser.close();
    }
  }

  buildReportHtml(data: {
    title: string;
    period: string;
    platform: string;
    metrics: Record<string, any>;
    topPosts: any[];
    aiInsights: string;
    charts?: string[]; // base64 chart images
  }): string {
    return `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', sans-serif; color: #1a1a2e; background: #fff; }
    .header { background: linear-gradient(135deg, #6366f1, #8b5cf6); color: white; padding: 40px; }
    .header h1 { font-size: 28px; font-weight: 700; }
    .header p { opacity: 0.8; margin-top: 8px; }
    .section { padding: 32px 40px; border-bottom: 1px solid #f0f0f0; }
    .section h2 { font-size: 18px; font-weight: 600; color: #6366f1; margin-bottom: 20px; }
    .metrics-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; }
    .metric-card { background: #f8f9ff; border-radius: 12px; padding: 20px; text-align: center; }
    .metric-card .value { font-size: 28px; font-weight: 700; color: #6366f1; }
    .metric-card .label { font-size: 12px; color: #666; margin-top: 4px; text-transform: uppercase; letter-spacing: 0.5px; }
    .insights { background: #f8f9ff; border-radius: 12px; padding: 24px; line-height: 1.7; }
    .post-item { display: flex; gap: 16px; padding: 16px 0; border-bottom: 1px solid #f0f0f0; }
    .post-content { flex: 1; font-size: 14px; color: #333; }
    .post-metrics { display: flex; gap: 12px; font-size: 12px; color: #666; margin-top: 8px; }
    .footer { padding: 24px 40px; text-align: center; color: #999; font-size: 12px; }
    .badge { display: inline-block; background: #6366f1; color: white; padding: 4px 12px; border-radius: 20px; font-size: 12px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>${data.title}</h1>
    <p>${data.platform} Analytics Report &bull; ${data.period}</p>
    <p style="margin-top:12px"><span class="badge">Generated by SocialPilot Pro</span></p>
  </div>

  <div class="section">
    <h2>Key Metrics</h2>
    <div class="metrics-grid">
      ${Object.entries(data.metrics).map(([key, value]) => `
        <div class="metric-card">
          <div class="value">${typeof value === 'number' ? value.toLocaleString() : value}</div>
          <div class="label">${key.replace(/_/g, ' ')}</div>
        </div>
      `).join('')}
    </div>
  </div>

  <div class="section">
    <h2>AI-Generated Insights</h2>
    <div class="insights">${data.aiInsights.replace(/\n/g, '<br>')}</div>
  </div>

  <div class="section">
    <h2>Top Performing Posts</h2>
    ${data.topPosts.slice(0, 5).map((post, i) => `
      <div class="post-item">
        <div style="font-size:20px;font-weight:700;color:#6366f1;min-width:32px">#${i + 1}</div>
        <div class="post-content">
          <div>${post.content?.slice(0, 150) || 'No content'}${post.content?.length > 150 ? '...' : ''}</div>
          <div class="post-metrics">
            <span>❤️ ${post.metrics?.likes || 0}</span>
            <span>💬 ${post.metrics?.comments || 0}</span>
            <span>🔁 ${post.metrics?.shares || 0}</span>
            <span>👁️ ${post.metrics?.reach || 0} reach</span>
            <span>📊 ${post.metrics?.engagementRate?.toFixed(2) || 0}% engagement</span>
          </div>
        </div>
      </div>
    `).join('')}
  </div>

  <div class="footer">
    <p>Generated on ${new Date().toLocaleDateString()} &bull; SocialPilot Pro &bull; Confidential</p>
  </div>
</body>
</html>`;
  }
}
